version: '3'

services:
  db:
    image: ${DB_IMAGE}
    container_name: database
    ports:
      - ${DB_PORTS}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - tct-32-network
    restart: always
    volumes:
      - ./database/data:/var/lib/postgresql/data

  backend:
    build: 
      dockerfile: Dockerfile
    image: ${APP_IMAGE}
    container_name: tct-32-app
    ports:
      - ${APP_PORTS}
    environment:
      - DATABASE_CLIENT=${DATABASE_CLIENT}
      - DATABASE_HOST=db
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_SSL={DATABASE_SSL}
    networks:
      - tct-32-network
    depends_on:
      - db
      - proxy
    restart: always
  proxy:
    container_name: web-server
    image: caddy:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
  website:
    image: ${WEB_IMAGE} 
    container_name: frontend
    ports:
      - ${webport}:3000
    environment:
      - port=${webport}
networks:
  tct-32-network:
